name: Embedded System Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: pip install pytest pyserial

      - name: Install socat for Virtual Serial Port
        run: sudo apt-get install -y socat

      - name: Start Virtual Serial Device
        run: socat -d -d pty,raw,echo=0 pty,raw,echo=0 &

      - name: Run Python Serial Tests
        run: pytest test_serial.py || echo "Tests failed, but continuing"
