name: Embedded System Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install C++ Dependencies
        run: sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build and Run C++ Tests
        run: |
          g++ -o test_example test_example.cpp -lgtest -lgtest_main -pthread
          ./test_example

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python Dependencies
        run: pip install pytest pyserial

      - name: Run Python Serial Tests
        run: pytest test_serial.py
